
name: Deploy GitHub Page

# Controls when the workflow will run
on:
  # Triggers the workflow on push for the "main" branch and only when index.html is changed
  push:
    branches: [ "main" ]
    paths: ["index.html"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
#sets permissions of GITHUB_TOKEN to allow deployments to GH pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages-deployment-${{github.repository}}
  cancel-in-progress: false


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-deploy"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'      
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
    
